description = "Base builder for Heroku-16 stack, based on ubuntu:16.04 base image"

[stack]
id = "heroku-16"
build-image = "fagiani/pack:16-build"
run-image = "fagiani/pack:16"

[lifecycle]
version = "0.13.1"

[[buildpacks]]
  id = "heroku/java"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/java?version=0.3.1&name=Java&stack=heroku-16"

[[buildpacks]]
  id = "heroku/scala"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/scala?version=0.3.1&name=Scala&stack=heroku-16"

[[buildpacks]]
  id = "heroku/ruby"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/ruby?version=0.3.1&name=Ruby&stack=heroku-16"

[[buildpacks]]
  id = "heroku/procfile"
  uri = "docker://docker.io/heroku/procfile-cnb:0.7.1"

[[buildpacks]]
  id = "heroku/python"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/python?version=0.3.1&name=Python&stack=heroku-16"

[[buildpacks]]
  id = "heroku/php-v192"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/php-v192?version=0.3.1&name=PHP&stack=heroku-16"

[[buildpacks]]
  id = "heroku/go"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/go?version=0.3.1&name=Go&stack=heroku-16"

[[buildpacks]]
  id = "heroku/nodejs"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/nodejs?version=0.3.1&name=Node&stack=heroku-16"

[[order]]
  [[order.group]]
    id = "heroku/ruby"
    version = "0.3.1"

  [[order.group]]
    id = "heroku/procfile"
    version = "0.7.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/python"
    version = "0.3.1"

  [[order.group]]
    id = "heroku/procfile"
    version = "0.7.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/scala"
    version = "0.3.1"

  [[order.group]]
    id = "heroku/procfile"
    version = "0.7.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/php-v192"
    version = "0.3.1"

  [[order.group]]
    id = "heroku/procfile"
    version = "0.7.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/go"
    version = "0.3.1"

  [[order.group]]
    id = "heroku/procfile"
    version = "0.7.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/nodejs"
    version = "0.3.1"

[[order]]
  [[order.group]]
    id = "heroku/java"
    version = "0.3.1"
