description = "Base builder for Heroku-16 stack, based on ubuntu:16.04 base image"

[stack]
id = "heroku-16"
build-image = "ghcr.io/fagiani/cnb/heroku-16:build"
run-image = "ghcr.io/fagiani/cnb/heroku-16:run"

[lifecycle]
version = "0.16.0"

[[buildpacks]]
  id = "heroku/java"
  uri = "https://buildpack-registry.s3.amazonaws.com/buildpacks/fagiani/heroku-java-buildpack-1.tgz"

[[buildpacks]]
  id = "heroku/scala"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/scala?version=0.3.1&name=Scala&stack=heroku-16"

[[buildpacks]]
  id = "heroku/ruby"
  uri = "https://buildpack-registry.s3.amazonaws.com/buildpacks/fagiani/heroku-buildpack-ruby-16.tgz"

[[buildpacks]]
  id = "heroku/procfile"
  uri = "docker://ghcr.io/fagiani/cnb/procfile:0.7.1"

[[buildpacks]]
  id = "heroku/python-v196"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/python-v196?version=0.3.1&name=Python&stack=heroku-16"

[[buildpacks]]
  id = "heroku/php-v190"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/php-v190?version=0.3.1&name=PHP&stack=heroku-16"

[[buildpacks]]
  id = "heroku/go-v153"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/go-v153?version=0.3.1&name=Go&stack=heroku-16"

[[buildpacks]]
  id = "heroku/nodejs-v184"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/nodejs-v184?version=0.3.1&name=Node&stack=heroku-16"

[[order]]
  [[order.group]]
    id = "heroku/ruby"
    version = "0.1.1"

  [[order.group]]
    id = "heroku/procfile"
    version = "0.7.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/python-v196"
    version = "0.3.1"

  [[order.group]]
    id = "heroku/procfile"
    version = "0.7.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/scala"
    version = "0.3.1"

  [[order.group]]
    id = "heroku/procfile"
    version = "0.7.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/php-v190"
    version = "0.3.1"

  [[order.group]]
    id = "heroku/procfile"
    version = "0.7.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/go-v153"
    version = "0.3.1"

  [[order.group]]
    id = "heroku/procfile"
    version = "0.7.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/nodejs-v184"
    version = "0.3.1"
    
  [[order.group]]
    id = "heroku/procfile"
    version = "0.7.1"
    optional = true
    
[[order]]
  [[order.group]]
    id = "heroku/java"
    version = "0.1.0"
